# .tmux.conf
# Tmux (Terminal Multiplexer) configuration file

# Miscellaneous {{{

set -sg escape-time 0 # fix VIm ESC delay

# begin window and pane indexing at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

set -g mouse on # mouse support

# }}}

# Keybinds {{{

# reload configuration file using r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# better pane splitting bindings (also opens in current directory)
unbind %
bind | split-window -h -c "#{pane_current_path}" # new pane to left
unbind '"'
bind - split-window -v -c "#{pane_current_path}" # new pane below
bind c new-window -c "#{pane_current_path}" # new window

# do not name windows automatically (use the ',' key)
set-option -g allow-rename off

# }}}

# Look and Feel {{{

# status bar position
set -g status-position bottom # Status bar position

# status bar colors
set -g status-style 'fg=#7EE300'
set -g status-left-length 20
set -g status-right-length 50

# status bar content
set -g status-left ' #S | ' # session name
set -g status-right '| %H:%M | %Y-%m-%d' # time and date

# window status
setw -g window-status-format ' #I:#W ' # window name and proess name
setw -g window-status-current-format '#[fg=#FFFFFF,bg=#0044FF] #I:#W '

# pane border colors
set -g pane-border-style 'fg=#F89000'
set -g pane-active-border-style 'fg=#FF0005'

# message styling
set -g message-style 'bg=#F3C230 fg=#0C050C'

# }}}

