# /home/parkervannah/.tmux.conf
# TMUX Terminal Multiplexer configuration file

# Miscellaneous {{{

set -sg escape-time 0 # fix VIm ESC delay

# begin window and pane indexing at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

set -g mouse on # mouse support

# }}}

# Keybinds {{{

# reload configuration file using r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# better pane splitting bindings (also opens in current directory)
unbind %
bind | split-window -h -c "#{pane_current_path}" # new pane to left
unbind '"'
bind - split-window -v -c "#{pane_current_path}" # new pane below
bind c new-window -c "#{pane_current_path}" # new window

# do not name windows automatically (use the ',' key)
set-option -g allow-rename off

# }}}

# Look and Feel {{{

# status bar position
set -g status-position bottom # Status bar position

# status bar colors
set -g status-style 'fg=#ff8787'
set -g status-left-length 20
set -g status-right-length 50

# status bar content
set -g status-left ' #S | '
set -g status-right '| %H:%M | %Y-%m-%d'

# window status
setw -g window-status-format ' #I:#W '
setw -g window-status-current-format '#[fg=#000000,bg=#ff8787] #I:#W '

# pane border colors
set -g pane-border-style 'fg=#875fd7'
set -g pane-active-border-style 'fg=#ff8787'

# message styling
set -g message-style 'bg=#836fff fg=#000000'

# }}}

