# /Users/parkervannah/.config/tmux/tmux.conf
# Tmux terminal multiplexer configuration file
# plain text configuration file

# Enable mouse support
set -g mouse on

# Start window and pane indexing at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# KEY BINDINGS ----------------------------------------------

# Prefix key (default: Ctrl+b)
# Rotate panes in window (default: Ctrl+o)
# Suspend (and exit) Tmux client (default: Ctrl+z)
# Move current pane to new window (default: !)
# Split current pane vertically (default: ")
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
# List all paste buffers (default: #)
# Rename current session (default: $)
# Split current pane horizontally (default: %)
unbind %
bind | split-window -h -c "#{pane_current_path}"
# Kill current window (default: &)
# Select window by index (default: ')
# Switch attached session to previous (default: ()
# Switch attached session to next (default: ))
# Rename current window (default: ,)
# Delete most recently copied buffer of text (default: -)!!!
# Edit window index (default: .)
# Select windows by index [0-9] (default: 0 to 9)
# Enter Tmux command prompt (default: :)
# Move to previously active pane (default: ;)
# Interactively choose buffer to paste (default: =)
# List key bindings (default: ?)
# Choose client to detach (default: D)
# Switch to previously attached client (default: L)
# Enter copy mode (default: [)
# Paste most recently copied buffer (default: ])
# Create a new window (default: c)
bind c new-window -c "#{pane_current_path}"
# Detach current client (default: d)
# Search for text in open windows (default: f)
# Display information about current window (default: i)
# Move to previously selected window (default: l)
# Mark current pane (default: m)
# Clear marked pane (default: M)
# Change to next window (default: n)
# Select next pane in current window (default: o)
# Change to previous window (default: p)
# Display pane indexes (default: q)
# Force redraw of attached client (default: r)!!!
# Interactively select new session (default: s)
# Show time (default: t)
# Interactively choose current window (default: w)
# Kill current pane (default: x)
# Toggle zoom of current pane [other panes disappear temporarily] (default: z)
# Swap current pane with previous pane (default: {)
# Swap current pane with next pane (default: })
# Enter copy mode and scroll one page up (default: Page Up)
# Select pane above, below, left, or right of current pane (default: up, down, left, right)
# Arrange panes to presets [1-7] (default: Cmd[M]-1 to Cmd[M]-7)
# Arrange current window in next preset layout (default: space)
# Move to next window with a bell or activity marker (default: Cmd[m]-n)
# Rotate panes in the current window backwards (default: Cmd[m]-o)
# Move to previous window with bell or activity marker. (default: Cmd[m]-p)
# Resize current pane in 1-cell steps (default: Ctrl[m]- up, down, left, right)
# Resize current pane in 5-cell steps (default: Cmd[m]- up, down, left, right)

# active configuration file reloading
unbind r
bind r source-file ~/.tmux.conf \; display "Configuration file reloaded."


# LOOK AND FEEL ---------------------------------

# Status bar position (default: bottom)
set -g status-position bottom
#set -g status-style 'bg=#FFBD67 fg=#6E0000'
#set -g status-left-length 20
#set -g status-right-length 50

